name: rooh
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  cloud_firestore: ^6.8.0
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  google_nav_bar: ^5.0.7
  dartz: ^0.10.1
  equatable: ^2.1.0
  responsive_framework: ^1.5.1
  firebase_auth: ^6.6.1
  google_sign_in: ^6.2.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900