// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcogDw7XxZE-bIYXcIwo9bWf1ImBdR47Q',
    appId: '1:1004975316486:web:b13cde7503408137712d87',
    messagingSenderId: '1004975316486',
    projectId: 'rooh-11',
    authDomain: 'rooh-11.firebaseapp.com',
    storageBucket: 'rooh-11.firebasestorage.app',
    measurementId: 'G-BDBFF1JJ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDlod_oy5RfiIwUru2kzjz_FrsPomMLMs',
    appId: '1:1004975316486:android:30f911a45f9c85ad712d87',
    messagingSenderId: '1004975316486',
    projectId: 'rooh-11',
    storageBucket: 'rooh-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7oOYQOpBZDhvdU9ILH-oc5LJ1QvQoyQ',
    appId: '1:1004975316486:ios:b9a0fc6a9921e588712d87',
    messagingSenderId: '1004975316486',
    projectId: 'rooh-11',
    storageBucket: 'rooh-11.firebasestorage.app',
    iosBundleId: 'com.example.rooh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi7oOYQOpBZDhvdU9ILH-oc5LJ1QvQoyQ',
    appId: '1:1004975316486:ios:b9a0fc6a9921e588712d87',
    messagingSenderId: '1004975316486',
    projectId: 'rooh-11',
    storageBucket: 'rooh-11.firebasestorage.app',
    iosBundleId: 'com.example.rooh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcogDw7XxZE-bIYXcIwo9bWf1ImBdR47Q',
    appId: '1:1004975316486:web:e7ae9734e7ad6b45712d87',
    messagingSenderId: '1004975316486',
    projectId: 'rooh-11',
    authDomain: 'rooh-11.firebaseapp.com',
    storageBucket: 'rooh-11.firebasestorage.app',
    measurementId: 'G-TZH8E3R5NN',
  );
}
